# Generated by Django 3.1.3 on 2020-12-12 15:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('city_image_link', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('covid_details', models.CharField(blank=True, max_length=100, null=True)),
                ('about_the_city', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('names_of_restaurants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), null=True, size=None)),
                ('about_the_restaurants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), null=True, size=None)),
                ('photo_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('restaurant_items', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None), size=None)),
                ('total_restaurants', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlacesToVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('names_of_places', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), null=True, size=None)),
                ('links_of_places', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('photo_links', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('about_the_places', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), null=True, size=None)),
                ('total_places', models.IntegerField(null=True)),
            ],
        ),
    ]
