# Generated by Django 3.1.3 on 2023-07-20 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='Cities',
        ),
    ]
