# Generated by Django 3.1.3 on 2020-12-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city_image_link',
            field=models.ImageField(null=True, upload_to='Places/city_images'),
        ),
    ]
