# Generated by Django 3.1.3 on 2020-12-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20201213_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city_image_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
