# Generated by Django 3.1.3 on 2023-07-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0002_auto_20230720_2017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelTable(
            name='city',
            table=None,
        ),
    ]
