# Generated by Django 3.1.3 on 2023-07-20 19:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0003_auto_20230720_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='about',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), blank=True, null=True, size=None),
        ),
    ]
