# Generated by Django 3.1.3 on 2023-07-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0006_auto_20230721_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='city_name',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='city',
            new_name='city_name',
        ),
    ]
