# Generated by Django 3.1.3 on 2023-07-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Places', '0007_auto_20230721_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='about',
            field=models.TextField(blank=True),
        ),
    ]
